repo: "link-card"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
    has_not:
      - "hr"
    search:
      - "Dosis"
      - "Dung Beetle"
      - "exclusively on dung"
      - "Learn more"
      - "Arthropoda"
      - "Superfamily"
      - "Scarabaeoidea"
      - "Scarabidae"

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['*', 'box-sizing', 'inherit']
      - ['.link-card']
      - ['.link-card:hover']
      - ['.link-card h2']
    search:
      - "Georgia"
      - "Dosis"
      - "block"
      - "inline-block"
      - "#785439"
      - "#cabdb2"
      - "#512200"
      - "#9a816d"
      - "#dcd4cd"
      - "#f0eee8"

screenshots:
  - path: "index.html"
    sizes: [320]

functionality:
  - path: 'index.html'
    tests:
      - |
        let link = $('.link-card');
        let oldBg = css(link).backgroundColor;

        hover('.link-card', function () {
          if (css(link).backgroundColor == oldBg) fail('The background colour of the card doesn’t change when hovered')
          pass();
        });
